name: Default Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches-ignore:
      - master

# Notes on what this workflow touches
# JOB_RUNNER: "ubuntu-latest"
# JOB_CONTAINER: "shrapk2/devops:latest"
# DEPLOYMENT_ENVIRONMENT: "any"

jobs:
  TF-Validation:
    runs-on: ubuntu-latest
    container:
      image: shrapk2/devops:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Terraform Validation - Infrastructure
        run: |
          terraform fmt -check
          terraform init -backend=false
          terraform validate
        working-directory: ./
      - name: Terraform Validation - Application Stack
        run: |
          terraform fmt -check
          terraform init -backend=false
          terraform validate
        working-directory: ./
